<?php
/**
 * The editopportunity view file of assetlib module of ZenTaoPMS.
 *
 * @copyright   Copyright 2009-2026 禅道软件（青岛）有限公司(ZenTao Software (Qingdao) Co., Ltd. www.zentao.net)
 * @license     ZPL(https://zpl.pub/page/zplv12.html) or AGPL(https://www.gnu.org/licenses/agpl-3.0.en.html)
 * @author      Guangming Sun <sunguangming@chandao.com>
 * @package     assetlib
 * @link        https://www.zentao.net
 */
namespace zin;

formPanel
(
    set::title($lang->assetlib->editOpportunity),
    on::change('[name="impact"], [name="chance"]', 'computeOpportunityIndex'),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->name),
        set::name('name'),
        set::value($opportunity->name),
        set::required(true)
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->source),
        picker
        (
            set::name('source'),
            set::items($lang->opportunity->sourceList),
            set::value($opportunity->source)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->type),
        picker
        (
            set::name('type'),
            set::items($lang->opportunity->typeList),
            set::value($opportunity->type)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->strategy),
        picker
        (
            set::name('strategy'),
            set::items($lang->opportunity->strategyList),
            set::value($opportunity->strategy)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->impact),
        picker
        (
            set::name('impact'),
            set::items($lang->opportunity->impactList),
            set::value($opportunity->impact)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->chance),
        picker
        (
            set::name('chance'),
            set::items($lang->opportunity->chanceList),
            set::value($opportunity->chance)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->ratio),
        input
        (
            set::name('ratio'),
            set::value($opportunity->ratio),
            set::readonly(true)
        )
    ),
    formGroup
    (
        set::width('1/2'),
        set::label($lang->opportunity->pri),
        priPicker
        (
            set::name('pri'),
            set::items($lang->opportunity->priList),
            set::value($opportunity->pri),
            set::disabled(true)
        )
    ),
    formGroup
    (
        set::label($lang->opportunity->desc),
        editor
        (
            set::name('desc'),
            set::value($opportunity->desc)
        )
    ),
    formGroup
    (
        set::label($lang->opportunity->prevention),
        editor
        (
            set::name('prevention'),
            set::value($opportunity->prevention)
        )
    ),
    formGroup
    (
        set::label($lang->opportunity->resolution),
        editor
        (
            set::name('resolution'),
            set::value($opportunity->resolution)
        )
    )
);
